name: RPM CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  package:
    name: "📦"
    runs-on: ubuntu-20.04
    container:
      image: quay.io/major/fedora-packager
      options: "--privileged"
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            /root/rpmbuild/SOURCES
          key: ${{ runner.os }}-${{ hashFiles('specs/*') }}

      - name: Build source RPMs
        run: |
          cd specs
          for SPEC in $(ls *.spec); do
            rpmdev-spectool -R -g $SPEC
            rpmbuild -bs $SPEC
          done
