name: RPM Build
on: push

jobs:
  build:
    container:
      image: https://quay.io/repository/major/fedora-packager:latest
      options: "--privileged"
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build RPMs
      run: ./build.sh

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v1.0.0
    #   with:
    #     name: Binary RPM
    #     path: ${{ steps.rpm.outputs.rpm_dir_path }}
